#!/bin/bash
# normdate -- Normlizes month field in date specification to three letters, 
# first letter capitalized. Exists with 0 if no error

monthNumToName()
{
    # Set the "month" variable to the appropriate value.
    case $1 in
        1) month="Jan";;
        2) month="Feb";;
        3) month="Mar";;
        4) month="Apr";;
        5) month="May";;
        6) month="Jun";;
        7) month="Jul";;
        8) month="Aug";;
        9) month="Sep";;
        10) month="Oct";;
        11) month="Nov";;
        12) month="Dec";;
        *) echo "$0: unknown month value $1 " >&2
           exit 1
        esac
        return 0
}

# Begin main script
# Input validation
if [ $# -eq 1 ]; then # accept date formats: MM/DD/YYYY, MM-DD-YYYY
    set -- $(echo $1 | sed 's/[\/\-]/ /g') # "--" is a bash built-in symbol 
                                           # to denote the end of command
                                           # options, and "set" is used to set
                                           # command parameters
fi
if [ $# -ne 3 ]; then
    echo "Usage: $0 month day year" >&2
    echo "Formats are June 16 1999 and 9 10 2000" >&2
    exit 1
fi
if [ $3 -le 999 ]; then
    echo "$0: expected 4-digit year value." >&2
    exit 1
fi

# Is the month format a number?
if [ -z $(echo $1|sed 's/[[:digit:]]//g') ]; then
    monthNumToName $1
else
# Normalize to first 3 letters, first upper- and the lowercase.
    month="$(echo $1|cut -c1|tr '[:lower:]' '[:upper:]')"
    month="$month$(echo $1|cut -c2-3 | tr '[:upper:]' '[:lower]')"
fi

echo $month $2 $3

exit 0
