#!/bin/bash
# shelltest -- A script to test some shell functions

press_enter()
{
    echo -en "\nPress Enter to continue"
    read
    clear
}
# Parameter expansion test
parameter=

##############
# PROGRAM MENU
##############
selection=
until [ "$seleciton" = "0" ]; do
    echo "
    PROGRAM MENU
    1 -- Do \${parameter:- \$HOME} test
    2 -- Do \${parameter:= \$HOME} test
    3 -- Do \${parameter:? \$USER} test
    4 -- Unset parameter
    
    0 -- Exit program
    "
    echo -n "Enter selection:"
    read seleciton 
    case $seleciton in 
        1 ) # ${parameter:- word}
            echo "parameter's initial value: $parameter" 
            echo 'Do echo ${parameter:- $HOME}:'
            echo ${parameter:- $HOME}
            echo "parameter now becomes: $parameter"
            press_enter
            ;;
        2 ) # ${parameter:= word}
            echo "parameter's initial value: $parameter" 
            echo 'Do echo ${parameter:= $HOME}:'
            echo ${parameter:= $HOME}
            echo "parameter now becomes: $parameter"
            press_enter
            ;;
        3 ) # ${parameter:? word}
            echo "parameter's initial value: $parameter" 
            echo 'Do echo ${parameter:? $USER}:' 
            echo ${parameter:? $USER}
            echo "parameter now becomes: $parameter"
            press_enter
            ;;
        4 ) echo 'unset parameter'
            unset parameter
            echo "parameter now becomes: $parameter"
            ;;
        * ) echo "Please enter selection above" 
            press_enter
    esac
done
