#!/bin/bash 
#trouble -- A script to learn how to find errors
set -x # Turn tracing on

number=1

if [ "$number" = "1" ]; then
    echo "Number equals 1"
else
    echo "Number does not equal 1"
fi
set +x # Turn tracing off