#!/bin/bash
# validAlphaNum--Ensure that input only consists of alphabetical and 
# numerical characters

validAlphaNum()
{
    # Validate arg: returns 0 if all upper+lower+digits; 1 otherwise

    # Remove all unacceptable chars
    validchars="$(echo $1 | sed -e 's/[^[:alnum:]]//g')"

    if [ "$validchars" = "$1" ]; then
        return 0
    else
        return 1
    fi
}

# Main script
read -p "Enter input:" -t 10 input

# Input validation
if ! validAlphaNum $input; then 
    echo "Please enter only alphanumerics"
else
    echo "Input is valid"
fi

exit 0